class KhetmehPlan {
  final String title;
  final String subtitle;
  final String rangeDescription;

  const KhetmehPlan({
    required this.title,
    required this.subtitle,
    required this.rangeDescription,
  });
}

class SurahInfo {
  final int number;
  final String name;
  final int page;

  const SurahInfo({
    required this.number,
    required this.name,
    required this.page,
  });
}

class JuzInfo {
  final int number;
  final int page;

  const JuzInfo({required this.number, required this.page});
}

const List<KhetmehPlan> khetmehPlans = [
  KhetmehPlan(
    title: '30 Days',
    subtitle: '1 juz per day',
    rangeDescription: 'Pages 1-604',
  ),
  KhetmehPlan(
    title: '15 Days',
    subtitle: '2 juz per day',
    rangeDescription: 'Pages 1-604 split in half',
  ),
  KhetmehPlan(
    title: 'Weekly',
    subtitle: '~4 juz per day',
    rangeDescription: 'Finish every Friday',
  ),
  KhetmehPlan(
    title: 'Weekend Focus',
    subtitle: 'Juz 1-15 Sat, 16-30 Sun',
    rangeDescription: 'Pages 1-302 then 303-604',
  ),
];

const List<SurahInfo> surahInfos = [
  SurahInfo(number: 1, name: "Al-Fatiha", page: 1),
  SurahInfo(number: 2, name: "Al-Baqara", page: 2),
  SurahInfo(number: 3, name: "Aal-Imran", page: 45),
  SurahInfo(number: 4, name: "An-Nisaa'", page: 69),
  SurahInfo(number: 5, name: "Al-Ma'ida", page: 95),
  SurahInfo(number: 6, name: "Al-An'am", page: 115),
  SurahInfo(number: 7, name: "Al-A'raf", page: 136),
  SurahInfo(number: 8, name: "Al-Anfal", page: 160),
  SurahInfo(number: 9, name: "Al-Tawba", page: 169),
  SurahInfo(number: 10, name: "Yunus", page: 187),
  SurahInfo(number: 11, name: "Hud", page: 199),
  SurahInfo(number: 12, name: "Yusuf", page: 212),
  SurahInfo(number: 13, name: "Ar-Ra'd", page: 225),
  SurahInfo(number: 14, name: "Ibrahim", page: 231),
  SurahInfo(number: 15, name: "Al-Hijr", page: 237),
  SurahInfo(number: 16, name: "An-Nahl", page: 242),
  SurahInfo(number: 17, name: "Al-Israa", page: 255),
  SurahInfo(number: 18, name: "Al-Kahf", page: 266),
  SurahInfo(number: 19, name: "Maryam", page: 277),
  SurahInfo(number: 20, name: "Ta-Ha", page: 284),
  SurahInfo(number: 21, name: "Al-Anbiya", page: 294),
  SurahInfo(number: 22, name: "Al-Hajj", page: 302),
  SurahInfo(number: 23, name: "Al-Muminun", page: 311),
  SurahInfo(number: 24, name: "An-Nur", page: 319),
  SurahInfo(number: 25, name: "Al-Furqan", page: 329),
  SurahInfo(number: 26, name: "Ash-Shuara", page: 335),
  SurahInfo(number: 27, name: "An-Naml", page: 345),
  SurahInfo(number: 28, name: "Al-Qasas", page: 354),
  SurahInfo(number: 29, name: "Al-Ankabut", page: 364),
  SurahInfo(number: 30, name: "Ar-Rum", page: 371),
  SurahInfo(number: 31, name: "Luqman", page: 377),
  SurahInfo(number: 32, name: "As-Sajdah", page: 381),
  SurahInfo(number: 33, name: "Al-Ahzab", page: 383),
  SurahInfo(number: 34, name: "Saba", page: 393),
  SurahInfo(number: 35, name: "Fatir", page: 399),
  SurahInfo(number: 36, name: "Yasin", page: 404),
  SurahInfo(number: 37, name: "As-Saffat", page: 410),
  SurahInfo(number: 38, name: "Sad", page: 417),
  SurahInfo(number: 39, name: "Az-Zumar", page: 422),
  SurahInfo(number: 40, name: "Ghafir", page: 431),
  SurahInfo(number: 41, name: "Fussilat", page: 439),
  SurahInfo(number: 42, name: "Ash-Shura", page: 445),
  SurahInfo(number: 43, name: "Az-Zukhruf", page: 451),
  SurahInfo(number: 44, name: "Ad-Dukhan", page: 457),
  SurahInfo(number: 45, name: "Al-Jathiya", page: 460),
  SurahInfo(number: 46, name: "Al-Ahqaf", page: 464),
  SurahInfo(number: 47, name: "Muhammad", page: 468),
  SurahInfo(number: 48, name: "Al-Fath", page: 472),
  SurahInfo(number: 49, name: "Al-Hujurat", page: 477),
  SurahInfo(number: 50, name: "Qaf", page: 479),
  SurahInfo(number: 51, name: "Az-Zariyat", page: 482),
  SurahInfo(number: 52, name: "At-Tur", page: 485),
  SurahInfo(number: 53, name: "An-Najm", page: 487),
  SurahInfo(number: 54, name: "Al-Qamar", page: 490),
  SurahInfo(number: 55, name: "Ar-Rahman", page: 493),
  SurahInfo(number: 56, name: "Al-Waqia", page: 496),
  SurahInfo(number: 57, name: "Al-Hadid", page: 499),
  SurahInfo(number: 58, name: "Al-Mujadilah", page: 504),
  SurahInfo(number: 59, name: "Al-Hashr", page: 507),
  SurahInfo(number: 60, name: "Al-Mumtahinah", page: 510),
  SurahInfo(number: 61, name: "As-Saff", page: 513),
  SurahInfo(number: 62, name: "Al-Jumu'ah", page: 515),
  SurahInfo(number: 63, name: "Al-Munafiqun", page: 516),
  SurahInfo(number: 64, name: "At-Taghabun", page: 518),
  SurahInfo(number: 65, name: "At-Talaq", page: 520),
  SurahInfo(number: 66, name: "At-Tahrim", page: 522),
  SurahInfo(number: 67, name: "Al-Mulk", page: 524),
  SurahInfo(number: 68, name: "Al-Qalam", page: 526),
  SurahInfo(number: 69, name: "Al-Haqqah", page: 529),
  SurahInfo(number: 70, name: "Al-Ma'arij", page: 531),
  SurahInfo(number: 71, name: "Nuh", page: 533),
  SurahInfo(number: 72, name: "Al-Jinn", page: 534),
  SurahInfo(number: 73, name: "Al-Muzzammil", page: 537),
  SurahInfo(number: 74, name: "Al-Muddaththir", page: 538),
  SurahInfo(number: 75, name: "Al-Qiyamah", page: 540),
  SurahInfo(number: 76, name: "Al-Insan", page: 542),
  SurahInfo(number: 77, name: "Al-Mursalat", page: 544),
  SurahInfo(number: 78, name: "An-Naba", page: 545),
  SurahInfo(number: 79, name: "An-Naziat", page: 547),
  SurahInfo(number: 80, name: "Abasa", page: 548),
  SurahInfo(number: 81, name: "At-Takwir", page: 550),
  SurahInfo(number: 82, name: "Al-Infitar", page: 551),
  SurahInfo(number: 83, name: "Al-Mutaffifin", page: 552),
  SurahInfo(number: 84, name: "Al-Inshiqaq", page: 553),
  SurahInfo(number: 85, name: "Al-Buruj", page: 554),
  SurahInfo(number: 86, name: "At-Tariq", page: 555),
  SurahInfo(number: 87, name: "Al-Ala", page: 556),
  SurahInfo(number: 88, name: "Al-Ghashiyah", page: 556),
  SurahInfo(number: 89, name: "Al-Fajr", page: 557),
  SurahInfo(number: 90, name: "Al-Balad", page: 559),
  SurahInfo(number: 91, name: "Ash-Shams", page: 559),
  SurahInfo(number: 92, name: "Al-Lail", page: 560),
  SurahInfo(number: 93, name: "Ad-Duha", page: 561),
  SurahInfo(number: 94, name: "Ash-Sharh", page: 561),
  SurahInfo(number: 95, name: "At-Tin", page: 562),
  SurahInfo(number: 96, name: "Al-Alaq", page: 562),
  SurahInfo(number: 97, name: "Al-Qadr", page: 563),
  SurahInfo(number: 98, name: "Al-Bayinah", page: 563),
  SurahInfo(number: 99, name: "Az-Zalzalah", page: 564),
  SurahInfo(number: 100, name: "Al-Adiyat", page: 564),
  SurahInfo(number: 101, name: "Al-Qariah", page: 565),
  SurahInfo(number: 102, name: "Al-Takathur", page: 565),
  SurahInfo(number: 103, name: "Al-Asr", page: 566),
  SurahInfo(number: 104, name: "Al-Humazah", page: 566),
  SurahInfo(number: 105, name: "Al-Fil", page: 566),
  SurahInfo(number: 106, name: "Quraish", page: 567),
  SurahInfo(number: 107, name: "Al-Ma'un", page: 567),
  SurahInfo(number: 108, name: "Al-Kauthar", page: 567),
  SurahInfo(number: 109, name: "Al-Kafirun", page: 568),
  SurahInfo(number: 110, name: "An-Nasr", page: 568),
  SurahInfo(number: 111, name: "Al-Masad", page: 568),
  SurahInfo(number: 112, name: "Al-Ikhlas", page: 569),
  SurahInfo(number: 113, name: "Al-Falaq", page: 569),
  SurahInfo(number: 114, name: "An-Nas", page: 569),
];

const List<JuzInfo> juzInfos = [
  JuzInfo(number: 1, page: 1),
  JuzInfo(number: 2, page: 22),
  JuzInfo(number: 3, page: 42),
  JuzInfo(number: 4, page: 62),
  JuzInfo(number: 5, page: 82),
  JuzInfo(number: 6, page: 102),
  JuzInfo(number: 7, page: 121),
  JuzInfo(number: 8, page: 142),
  JuzInfo(number: 9, page: 162),
  JuzInfo(number: 10, page: 182),
  JuzInfo(number: 11, page: 201),
  JuzInfo(number: 12, page: 222),
  JuzInfo(number: 13, page: 242),
  JuzInfo(number: 14, page: 262),
  JuzInfo(number: 15, page: 282),
  JuzInfo(number: 16, page: 302),
  JuzInfo(number: 17, page: 322),
  JuzInfo(number: 18, page: 342),
  JuzInfo(number: 19, page: 362),
  JuzInfo(number: 20, page: 382),
  JuzInfo(number: 21, page: 402),
  JuzInfo(number: 22, page: 422),
  JuzInfo(number: 23, page: 442),
  JuzInfo(number: 24, page: 462),
  JuzInfo(number: 25, page: 482),
  JuzInfo(number: 26, page: 502),
  JuzInfo(number: 27, page: 522),
  JuzInfo(number: 28, page: 542),
  JuzInfo(number: 29, page: 562),
  JuzInfo(number: 30, page: 582),
];
