class KhetmehPlan {
  final String title;
  final String subtitle;
  final String rangeDescription;

  const KhetmehPlan({
    required this.title,
    required this.subtitle,
    required this.rangeDescription,
  });
}

class SurahInfo {
  final int number;
  final String name;
  final int page;

  const SurahInfo({
    required this.number,
    required this.name,
    required this.page,
  });
}

class JuzInfo {
  final int number;
  final int page;

  const JuzInfo({required this.number, required this.page});
}

const List<KhetmehPlan> khetmehPlans = [
  KhetmehPlan(
    title: '30 Days',
    subtitle: '1 juz per day',
    rangeDescription: 'Pages 1-604',
  ),
  KhetmehPlan(
    title: '15 Days',
    subtitle: '2 juz per day',
    rangeDescription: 'Pages 1-604 split in half',
  ),
  KhetmehPlan(
    title: 'Weekly',
    subtitle: '~4 juz per day',
    rangeDescription: 'Finish every Friday',
  ),
  KhetmehPlan(
    title: 'Weekend Focus',
    subtitle: 'Juz 1-15 Sat, 16-30 Sun',
    rangeDescription: 'Pages 1-302 then 303-604',
  ),
];

const List<SurahInfo> surahInfos = [
  SurahInfo(number: 1, name: "Al-Fatihah", page: 1),
  SurahInfo(number: 2, name: "Al-Baqarah", page: 2),
  SurahInfo(number: 3, name: "Ali 'Imran", page: 50),
  SurahInfo(number: 4, name: "An-Nisa", page: 77),
  SurahInfo(number: 5, name: "Al-Ma'idah", page: 106),
  SurahInfo(number: 6, name: "Al-An'am", page: 128),
  SurahInfo(number: 7, name: "Al-A'raf", page: 151),
  SurahInfo(number: 8, name: "Al-Anfal", page: 177),
  SurahInfo(number: 9, name: "At-Tawbah", page: 187),
  SurahInfo(number: 10, name: "Yunus", page: 208),
  SurahInfo(number: 11, name: "Hud", page: 221),
  SurahInfo(number: 12, name: "Yusuf", page: 235),
  SurahInfo(number: 13, name: "Ar-Ra'd", page: 249),
  SurahInfo(number: 14, name: "Ibrahim", page: 255),
  SurahInfo(number: 15, name: "Al-Hijr", page: 262),
  SurahInfo(number: 16, name: "An-Nahl", page: 267),
  SurahInfo(number: 17, name: "Al-Isra", page: 282),
  SurahInfo(number: 18, name: "Al-Kahf", page: 293),
  SurahInfo(number: 19, name: "Maryam", page: 305),
  SurahInfo(number: 20, name: "Taha", page: 312),
  SurahInfo(number: 21, name: "Al-Anbya", page: 322),
  SurahInfo(number: 22, name: "Al-Hajj", page: 332),
  SurahInfo(number: 23, name: "Al-Mu'minun", page: 342),
  SurahInfo(number: 24, name: "An-Nur", page: 350),
  SurahInfo(number: 25, name: "Al-Furqan", page: 359),
  SurahInfo(number: 26, name: "Ash-Shu'ara", page: 367),
  SurahInfo(number: 27, name: "An-Naml", page: 377),
  SurahInfo(number: 28, name: "Al-Qasas", page: 385),
  SurahInfo(number: 29, name: "Al-'Ankabut", page: 396),
  SurahInfo(number: 30, name: "Ar-Rum", page: 404),
  SurahInfo(number: 31, name: "Luqman", page: 411),
  SurahInfo(number: 32, name: "As-Sajdah", page: 415),
  SurahInfo(number: 33, name: "Al-Ahzab", page: 418),
  SurahInfo(number: 34, name: "Saba", page: 428),
  SurahInfo(number: 35, name: "Fatir", page: 434),
  SurahInfo(number: 36, name: "Ya-Sin", page: 440),
  SurahInfo(number: 37, name: "As-Saffat", page: 446),
  SurahInfo(number: 38, name: "Sad", page: 453),
  SurahInfo(number: 39, name: "Az-Zumar", page: 458),
  SurahInfo(number: 40, name: "Ghafir", page: 467),
  SurahInfo(number: 41, name: "Fussilat", page: 477),
  SurahInfo(number: 42, name: "Ash-Shuraa", page: 483),
  SurahInfo(number: 43, name: "Az-Zukhruf", page: 489),
  SurahInfo(number: 44, name: "Ad-Dukhan", page: 496),
  SurahInfo(number: 45, name: "Al-Jathiyah", page: 499),
  SurahInfo(number: 46, name: "Al-Ahqaf", page: 502),
  SurahInfo(number: 47, name: "Muhammad", page: 507),
  SurahInfo(number: 48, name: "Al-Fath", page: 511),
  SurahInfo(number: 49, name: "Al-Hujurat", page: 515),
  SurahInfo(number: 50, name: "Qaf", page: 518),
  SurahInfo(number: 51, name: "Adh-Dhariyat", page: 520),
  SurahInfo(number: 52, name: "At-Tur", page: 523),
  SurahInfo(number: 53, name: "An-Najm", page: 526),
  SurahInfo(number: 54, name: "Al-Qamar", page: 528),
  SurahInfo(number: 55, name: "Ar-Rahman", page: 531),
  SurahInfo(number: 56, name: "Al-Waqi'ah", page: 534),
  SurahInfo(number: 57, name: "Al-Hadid", page: 537),
  SurahInfo(number: 58, name: "Al-Mujadila", page: 542),
  SurahInfo(number: 59, name: "Al-Hashr", page: 545),
  SurahInfo(number: 60, name: "Al-Mumtahanah", page: 549),
  SurahInfo(number: 61, name: "As-Saf", page: 551),
  SurahInfo(number: 62, name: "Al-Jumu'ah", page: 553),
  SurahInfo(number: 63, name: "Al-Munafiqun", page: 554),
  SurahInfo(number: 64, name: "At-Taghabun", page: 556),
  SurahInfo(number: 65, name: "At-Talaq", page: 558),
  SurahInfo(number: 66, name: "At-Tahrim", page: 560),
  SurahInfo(number: 67, name: "Al-Mulk", page: 562),
  SurahInfo(number: 68, name: "Al-Qalam", page: 564),
  SurahInfo(number: 69, name: "Al-Haqqah", page: 566),
  SurahInfo(number: 70, name: "Al-Ma'arij", page: 568),
  SurahInfo(number: 71, name: "Nuh", page: 570),
  SurahInfo(number: 72, name: "Al-Jinn", page: 572),
  SurahInfo(number: 73, name: "Al-Muzzammil", page: 574),
  SurahInfo(number: 74, name: "Al-Muddaththir", page: 575),
  SurahInfo(number: 75, name: "Al-Qiyamah", page: 577),
  SurahInfo(number: 76, name: "Al-Insan", page: 578),
  SurahInfo(number: 77, name: "Al-Mursalat", page: 580),
  SurahInfo(number: 78, name: "An-Naba", page: 582),
  SurahInfo(number: 79, name: "An-Nazi'at", page: 583),
  SurahInfo(number: 80, name: "'Abasa", page: 585),
  SurahInfo(number: 81, name: "At-Takwir", page: 586),
  SurahInfo(number: 82, name: "Al-Infitar", page: 587),
  SurahInfo(number: 83, name: "Al-Mutaffifin", page: 587),
  SurahInfo(number: 84, name: "Al-Inshiqaq", page: 589),
  SurahInfo(number: 85, name: "Al-Buruj", page: 590),
  SurahInfo(number: 86, name: "At-Tariq", page: 591),
  SurahInfo(number: 87, name: "Al-A'la", page: 591),
  SurahInfo(number: 88, name: "Al-Ghashiyah", page: 592),
  SurahInfo(number: 89, name: "Al-Fajr", page: 593),
  SurahInfo(number: 90, name: "Al-Balad", page: 594),
  SurahInfo(number: 91, name: "Ash-Shams", page: 595),
  SurahInfo(number: 92, name: "Al-Layl", page: 595),
  SurahInfo(number: 93, name: "Ad-Duhaa", page: 596),
  SurahInfo(number: 94, name: "Ash-Sharh", page: 596),
  SurahInfo(number: 95, name: "At-Tin", page: 597),
  SurahInfo(number: 96, name: "Al-'Alaq", page: 597),
  SurahInfo(number: 97, name: "Al-Qadr", page: 598),
  SurahInfo(number: 98, name: "Al-Bayyinah", page: 598),
  SurahInfo(number: 99, name: "Az-Zalzalah", page: 599),
  SurahInfo(number: 100, name: "Al-'Adiyat", page: 599),
  SurahInfo(number: 101, name: "Al-Qari'ah", page: 600),
  SurahInfo(number: 102, name: "At-Takathur", page: 600),
  SurahInfo(number: 103, name: "Al-'Asr", page: 601),
  SurahInfo(number: 104, name: "Al-Humazah", page: 601),
  SurahInfo(number: 105, name: "Al-Fil", page: 601),
  SurahInfo(number: 106, name: "Quraysh", page: 602),
  SurahInfo(number: 107, name: "Al-Ma'un", page: 602),
  SurahInfo(number: 108, name: "Al-Kawthar", page: 602),
  SurahInfo(number: 109, name: "Al-Kafirun", page: 603),
  SurahInfo(number: 110, name: "An-Nasr", page: 603),
  SurahInfo(number: 111, name: "Al-Masad", page: 603),
  SurahInfo(number: 112, name: "Al-Ikhlas", page: 604),
  SurahInfo(number: 113, name: "Al-Falaq", page: 604),
  SurahInfo(number: 114, name: "An-Nas", page: 604),
];

const List<JuzInfo> juzInfos = [
  JuzInfo(number: 1, page: 1),
  JuzInfo(number: 2, page: 22),
  JuzInfo(number: 3, page: 42),
  JuzInfo(number: 4, page: 62),
  JuzInfo(number: 5, page: 82),
  JuzInfo(number: 6, page: 102),
  JuzInfo(number: 7, page: 121),
  JuzInfo(number: 8, page: 142),
  JuzInfo(number: 9, page: 162),
  JuzInfo(number: 10, page: 182),
  JuzInfo(number: 11, page: 201),
  JuzInfo(number: 12, page: 222),
  JuzInfo(number: 13, page: 242),
  JuzInfo(number: 14, page: 262),
  JuzInfo(number: 15, page: 282),
  JuzInfo(number: 16, page: 302),
  JuzInfo(number: 17, page: 322),
  JuzInfo(number: 18, page: 342),
  JuzInfo(number: 19, page: 362),
  JuzInfo(number: 20, page: 382),
  JuzInfo(number: 21, page: 402),
  JuzInfo(number: 22, page: 422),
  JuzInfo(number: 23, page: 442),
  JuzInfo(number: 24, page: 462),
  JuzInfo(number: 25, page: 482),
  JuzInfo(number: 26, page: 502),
  JuzInfo(number: 27, page: 522),
  JuzInfo(number: 28, page: 542),
  JuzInfo(number: 29, page: 562),
  JuzInfo(number: 30, page: 582),
];
